jenkins-infra/cn.jenkins.io

Makefile
In my first time to run 'make run', get error information about lack scripts permission.
=> handle scripts permission

Makefile
=> fixes makefile errors

Jenkinsfile, Makefile, content/_config/site.yml
This PR build and continuously deploy this website on jenkins.io/cn, it follows the same approach than [jenkins.io](https://github.com/jenkins-infra/jenkins.io).
=> Add a profile to build a jenkins.io/cn website

content/artwork/index.html.haml
=> artwork page translation

content/projects/index.adoc
=> translate into Chiense: content/projects/index #25

.github/PULL_REQUEST_TEMPLATE.md
=> Add pull-template

content/solutions/java.adoc
=> Add localization for content/solutions/java.adoc

content/sigs/chinese-localization/index.adoc
fix Chinese  wrong default encoding
Fix #53
=> add encoding declaration UTF-8

content/projects/gsoc/mentors.adoc
=> Add translation for /projects/gsoc/mentor.adoc

content/press.adoc, content/project/conduct.adoc
Governance page 内容较多，切换到另外的 PR
=> Conduct Page work

content/event-calendar.html.haml
=> Add calendar translate page

Gemfile, Gemfile.lock, content/_data/logo/kongfu.yml, package-lock.json
=> Fix the broken link of artwork kongfu

.github/PULL_REQUEST_TEMPLATE.md
=> Add checklist item and more description

content/_messages/messages_zh-CN.yml, content/_partials/toptoolbar.html.haml
=> nav up to date with io site

content/doc/developer/tutorial/create.adoc, content/doc/developer/tutorial/extend.adoc, content/doc/developer/tutorial/index.adoc, content/doc/developer/tutorial/prepare.adoc, content/doc/developer/tutorial/run.adoc
=> Fix #67:Update bad grammar and outdated content under content/doc/developer/tutorial/×

content/_layouts/frame.html.haml
Issue #81 
Fix link at page footer.
=> fix link at footer.

content/blog/2018/08/2018-08-21-contributor-summit-nice.adoc
=> Fix missing the file meta info

content/blog/2018/12/2018-12-10-the-official-Docker-image.adoc
=> [WEBSITE-603] Add translation for the official Docker image

content/blog/2018/08/2018-08-23-speaker-blog-casc-part-1.adoc
See also https://github.com/jenkins-infra/wechat/pull/16
=> typo fixes

.github/PULL_REQUEST_TEMPLATE.md
=> Fix the wrong translation-spec link

content/doc/pipeline/examples.html.haml
=> Translation for pipeline example page

content/_messages/messages_zh-CN.yml, content/_partials/toptoolbar.html.haml
=> Add languages menu

README.adoc
modify the website url to:
http://jenkins.io/zh/
=> modify the website url

content/sigs/index.html.haml
fixes wrong links for learn more
=> Localization the SIGs home page

content/blog/2018/12/2018-12-10-outreachy-audit-log-plugin.adoc
=> Add blog outreach-autit-log-plugin

content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
原文地址：https://jenkins.io/blog/2018/12/14/java11-preview-availability/
=> [WEBSITE-606] - Translate: java11 preview availability

content/_data/authors/linuxsuren.adoc, content/_ext/authorship.rb, content/_layouts/post.html.haml
fixes #126 
There's no the original article link yet.
=> Add translator infor in blog layout

content/sigs/pipeline-authoring/index.adoc
=> Translate task: sigs/pipeline-authoring/index.adoc

content/blog/2018/12/2018-12-14-java11-preview-availability.adoc
=> Add translator and fix some errors 

content/_data/authors/raychou1203.adoc
=> Add myself as a translator

content/_partials/toptoolbar.html.haml
=> fix subprojects toptoolbar

content/blog/2019/01/2019-01-08-mpl-modular-pipeline-library.adoc
=> fix image path on blog/2019/01/08/mpl-modular-pipeline-library.adoc

content/node/index.html.haml
=> translate description on jenkins.io/zh/node/

content/projects/jcasc/index.adoc
=> add Translate content/projects/jcasc/index.adoc page

content/projects/jenkins-x/index.adoc
=> Add content/projects/jenkins-x

content/download/index.html.haml
=> Change the link to zh

content/_partials/projectcarousel.html.haml, content/index.html.haml
=> Change the land page with cdf

content/download/index.html.haml
=> Use relative links instead of abs

content/node/index.html.haml
=> Add wechat to blog home page

content/_partials/changelog-changes.html.haml, content/_partials/changelog-changes.xml.haml, content/_partials/changelog-header.html
=> Add localization for changelog page

content/download/index.html.haml
=> Fix the wrong links in the page of download

content/blog/2019/03/2019-03-12-cdf-launch.adoc
=> Fix link display issues

content/doc/developer/404.html.haml, content/doc/developer/book.html.haml, content/doc/developer/guides.html.haml, content/doc/developer/index.html.haml, content/doc/index.adoc, content/doc/thank-you-for-your-feedback.adoc, content/doc/upgrade-guide.html.haml, scripts/generate-handbook-pdf
=> Add localization for doc

content/_layouts/advisory.html.haml, content/_layouts/chapter.html.haml, content/_layouts/developerbook.html.haml, content/_layouts/developerchapter.html.haml, content/_layouts/developerguide.html.haml, content/_layouts/documentation.html.haml, content/_layouts/frame.html.haml, content/_layouts/section.html.haml
=> Add localization for layouts

content/doc/book/pipeline/syntax.adoc
=> Fix syntax on /doc/book/pipeline/syntax/

content/_data/authors/p01son6415.adoc, content/blog/2019/03/2019-04-03-security-advisory.adoc
=> Translate task:  Security spring cleaning

content/doc/book/pipeline/jenkinsfile.adoc
=> Fix content/doc/book/pipeline/jenkinsfile

content/doc/developer/plugin-development/pipeline-integration.adoc
=> [维护]: typo fix

content/doc/developer/internationalization/i18n-groovy-views.adoc, content/doc/developer/internationalization/i18n-jelly-views.adoc, content/doc/developer/internationalization/index.adoc
=> translation for internationalization related pages

content/sigs/chinese-localization/index.adoc
=> add donhui as a new member

content/_layouts/project.html.haml
=> Fix the wrong link

content/_data/authors/donhui.adoc, content/_data/authors/markewaite.adoc, content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc
=> blog translation: Jenkins Documentation Special Interest Group

content/doc/book/pipeline/index.adoc
=> 修正一些文字和格式错误

content/blog/2019/05/2019-05-11-docs-sig-announcement.adoc
=> fix:review 不翻译

content/css/jenkins.css
=> Update jenkins.css from jenkins.io

content/_data/changelogs/lts.yml
=> Add changelog for 2.164.3

content/blog/2019/03/2019-03-11-let-s-celebrate-java-11-support.adoc
=> Translate task:blog/2019/03/let-s-celebrate-java-11-support

content/doc/book/managing/security.adoc
fix jenkins-infra#203 extra letter e, please review. thanks.
=> fix jenkins-infra#203 extra letter e

content/doc/book/pipeline/shared-libraries.adoc
=> 修正[扩展共享库 ]页面部分空格、标点及翻译问题

content/_data/changelogs/lts.yml
=> To restore this feature, install the CCtray XML Plugin (issue 40750) 有误翻译修复 (#221)

content/blog/2019/07/2019-07-05-jenkins-pipeline-stage-result-visualization-improvements.adoc
=> Add blog jenkins-pipeline-stage-result-visualization-improvements

content/blog/2019/08/2019-08-30-jenkins-cli.adoc
=> Add a blog about jcli

content/doc/book/pipeline/getting-started.adoc, content/doc/book/pipeline/jenkinsfile.adoc
=> 改进 doc/book/pipeline/getting-started 的翻译文本，增加内容

content/doc/upgrade-guide/2.138.adoc
=> 翻译升级指南 Upgrading to Jenkins LTS 2.138.x  

content/blog/2019/07/2019-07-02-plugin-management-tool-alpha-release.adoc
=> 翻译 Blog 20190702 plugin-management-tool-alpha-release

content/index.html.haml
=> 翻译 Jenkins 首页与CDF相关内容

content/index.html.haml
Reverts jenkins-infra/cn.jenkins.io#246
=> Revert "翻译 Jenkins 首页与CDF相关内容"

content/index.html.haml
=> 修复首页出现报错问题

content/blog/2019/07/2019-07-02-plugin-management-tool-alpha-release.adoc
=> 修复plugin-management-tool-alpha-release翻译中存储库 README.md 超链接格式错误问题修复

.github/PULL_REQUEST_TEMPLATE.md
=> 修改 PR 模板，使得注释语句不用人工删除

content/_data/changelogs/weekly.yml
=> add weekly changelog 2.215~2.219

content/doc/pipeline/tour/hello-world.adoc
=> 修改链接为中文站点链接

content/_data/changelogs/weekly.yml
=> add weekly changelog 2.222

content/_layouts/frame.html.haml
=> add weibo link

content/_data/changelogs/lts.yml
=> add lts changelog 2.204.6 & 2.222.1

content/_data/authors/linuxsuren.adoc
Here is the link https://twitter.com/LinuxSuRen
=> Change my Twitter ID

content/_data/changelogs/lts.yml
=> Reduce changelog yellowness in lts changelog

content/doc/upgrade-guide/2.222.adoc
=> 增加 lts 2.222.1 升级指南

content/doc/upgrade-guide.html.haml
=> 升级指南页面个版本的详细升级指导链接修复

content/_config/site.yml
Equivalent of https://github.com/jenkins-infra/jenkins.io/commit/7da9816e4770f3009b43b776a46f7c5a447a4fe5
Due to fastly being enabled
=> Switch base url to www

scripts/ruby
=> update ruby to 2.6

OWNERS, content/_data/changelogs/OWNERS
=> Add owners file

content/doc/book/pipeline/syntax.adoc
=> 修改when语法下的拼写错误

content/doc/book/blueocean/index.adoc
=> blueocean/index: fix typo
